let strip = neopixel.create(DigitalPin.P1, 30, NeoPixelMode.RGB)
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
strip.show()
basic.pause(240000)
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(53, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(24, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(53, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(29, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(34, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(28, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(39, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(33, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(44, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(38, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(49, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(43, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(54, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(48, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.pause(60000)
strip.setPixelColor(59, neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(240000)
strip.setPixelColor(58, neopixel.colors(NeoPixelColors.Orange))
strip.show()
basic.forever(function () {
	
})
